name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        charm: [pilot, ingressgateway]

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install tox
    - run: tox -e ${{ matrix.charm }}

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - uses: balchua/microk8s-actions@v0.2.2
      with:
        channel: 'latest/stable'
        addons: '["dns", "storage", "rbac", "metallb:10.64.140.43-10.64.140.49"]'

    - name: Install dependencies
      run: |
        set -eux
        sudo pip3 install charmcraft==1.0.0
        sudo snap install juju --classic
        sudo snap install juju-helpers --classic
        sudo snap install juju-wait --classic

    # Avoid race condition with storage taking a long time to initialize
    - name: Wait for storage
      run: |
        sg microk8s -c 'microk8s kubectl rollout status deployment/hostpath-provisioner -n kube-system'

    - name: Set up Istio
      run: |
        set -eux
        sg microk8s -c 'juju bootstrap microk8s uk8s'
        juju add-model istio-system microk8s --config update-status-hook-interval=10s
        juju bundle deploy --build
        sleep 10
        kubectl patch role -n istio-system istio-ingressgateway-operator -p '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"name":"istio-ingressgateway-operator"},"rules":[{"apiGroups":["*"],"resources":["*"],"verbs":["*"]}]}'
        juju wait -wvt 300 --retry_errors 20

    - name: Deploy bookinfo application
      run: |
        set -eux
        kubectl label namespace default istio-injection=enabled
        kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.5/samples/bookinfo/platform/kube/bookinfo.yaml
        kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.5/samples/bookinfo/networking/bookinfo-gateway.yaml
        kubectl wait --for=condition=available deployment --all --timeout=5m
        sleep 15

    - name: Ensure bookinfo came up
      run: curl -fv http://10.64.140.43/productpage

    - run: juju status
      if: failure()

    - name: Get pod statuses
      run: kubectl get all -A
      if: failure()

    - name: Describe deployments
      run: kubectl describe deployments -A
      if: failure()

    - name: Describe replicasets
      run: kubectl describe replicasets -A
      if: failure()

    - name: Get istio-pilot logs
      run: kubectl logs -n istio-system --tail 1000 -ljuju-app=istio-pilot
      if: failure()

    - name: Get istio-pilot operator logs
      run: kubectl logs -n istio-system --tail 1000 -ljuju-operator=istio-pilot
      if: failure()

    - name: Get istio-ingressgateway logs
      run: kubectl logs -n istio-system --tail 1000 -ljuju-app=istio-ingressgateway
      if: failure()

    - name: Get istio-ingressgateway operator logs
      run: kubectl logs -n istio-system --tail 1000 -ljuju-operator=istio-ingressgateway
      if: failure()
